### ISSUE TITLE
'albersusa' for R 3.4.1

### ISSUE THREAD

**Issue by matiram** [hrbrmstr/albersusa#13]
I am trying to install 'albersusa' and I get message that it is not available for R version 3.4.1?

Warning in install.packages :
  package ‘albersusa’ is not available (for R version 3.4.1)

**Comment by hrbrmstr** [comment]
It is not on CRAN. It has never been on CRAN. It will likely not be on CRAN
anytime soon. Tis a reason the README.md has the installation guidelines
that it has.

**Comment by matiram** [comment]
Thanks
