### ISSUE TITLE
Error: "unable to find an inherited method..."

### ISSUE THREAD

**Issue by drcanak** [hrbrmstr/albersusa#17]
Following this blog post:

https://rud.is/b/2019/01/30/fast-static-maps-built-with-r/

Following this block of code:

hi <- select(filter(area_pct, state == "HI"), lon, lat)
hi <- points_elided(hi)
area_pct[area_pct$state == "HI", c("lon", "lat")] <- hi

I get the following error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘proj4string’ for signature ‘"tbl_df"’

I am using the most recent development version of albersusa (‘0.3.1’), R version 3.5.2, all packages up-to-date.

**Comment by hrbrmstr** [comment]
a local `git status` does indeed show you are spot-on! #ty!

I've pushed a new update (just now)
